version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: assignment27_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: assignment27_server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/capstone_relationships_db
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: assignment27_client
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

volumes:
  mongo_data:
